### ISSUE TITLE
Incorrect names of FLEx tier names

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [BrownCLPS/LingView#15]
The names of tiers in files from FLEx are the following:

> Palabra a'ingae (dureno)
> Morfema (texto) a'ingae (dureno)
> Morfema (forma típico) a'ingae (dureno)
> Glosa de morfema inglés
> Glosa de morfema español
> Frase inglés
> Frase español

I don't know which parts are generated automatically, and which are hardcoded but the Spanish tier names are ungrammatical at times. The correct versions are: 

> palabra **en** a'ingae (ortografía nueva)
> morfema (en el texto) **en** a'ingae (ortografía nueva)
> morfema (forma **típica**) **en** a'ingae (ortografía nueva)
> glosa de morfema **en** inglés
> glosa de morfema **en** español
> frase **en** inglés
> frase **en** español

I bolded the particularly egregious mistakes. I also think it makes sense to make the first letter lowercase because these aren't beginnings of new sentences.

I don't know how much of this can be changed, but please have a look at this if you have a moment guys!

**Comment by sciepsilon** [comment]
Yeah, most of this is auto-generated, and should be pretty easy to fix. The relevant file is `preprocessing/tier_registry.js'.

**Comment by sciepsilon** [comment]
Correction: "morfema" is a masculine noun, so "morfema típic**o**" is correct. Source: https://www.spanishdict.com/translate/morfema It's common for Greek-derived nouns ending in "ma" to be masculine.

**Comment by sciepsilon** [comment]
Oh, um, duh. "típica" modifies "forma", which is a feminine noun. Whoops.

**Comment by sciepsilon** [comment]
Holly, I sent you some comments via Slack. Copying them here for posterity: 

Looks good. There are a couple extra changes to make:

For the “txt” type: This type is the morpheme spelled the way it was in the transcript. This is usually identical to the citation form of the morpheme (“cf” type), but not always. Maks recommends “morfema (en el texto)” for this tier, but the added meaning from “(text)” or “(in the text)” doesn’t seem particularly clear to me, so maybe we’re better off keeping it short and just saying “morfema”. Use your judgment.

Maks also uses “ortografía nueva” instead of “dureno”, so let’s do that, and we might want to make a similar change to use “ortografía Borman” instead of “borman”.

Finally, I realized there’s a bug in the code! We’re doing .toLowerCase() to mean “don’t capitalize the first letter”, but that has the unfortunate side effect of making “borman” lowercase. Let’s change the code so that decodeTier’s and decodeLang’s results have the same upper/lower case as if they appeared in a sentence. So, for English UI, the words A’ingae/Spanish/English/Borman should be capitalized and everything else should be lowercase; for Spanish UI, only the word Borman should be capitalized. Then in getTierName, we should change the first letter of the tier name to be a capital letter, regardless of what language UI we’re working in. 

~~Oh, and I think Maks was wrong about one of the corrections, and it should still be “morfema típico”. According to SpanishDict, “morfema” is a masculine noun despite ending in “a”. https://www.spanishdict.com/translate/morfema~~
Nope, “forma” is feminine, so Maks is right and it should be “típica”

**Comment by hollyyuqizheng** [comment]
Closed with #62
