### ISSUE TITLE
Linking to a specific line in a written text without AV

### ISSUE THREAD

**Issue by maksymilian-dabkowski** [BrownCLPS/LingView#36]

**Comment by sciepsilon** [comment]
Mimic what we do on timed stories. Currently, if the story has AV, it gets a clickable timestamp next to each sentence, and if there's no audio or video, each sentence is bare. If the story doesn't have AV, we should include a sentence number instead of the timestamp. When someone clicks the sentence number, it should be added to the url with a ? before it. When loading a page with a ? in the url, the page should scroll to the corresponding sentence.

**Comment by hollyyuqizheng** [comment]
#56 and then #57
