### ISSUE TITLE
Fix nav bar for narrow screens

### ISSUE THREAD

**Issue by sciepsilon** [BrownCLPS/LingView#70]
When the screen is narrow, the nav bar text flows onto the next line, resulting in white text on a light background. This is hard to read. We should fix this so that the nav bar is still easy to use on narrow screens. 

We could fix it several ways:

- replace the nav bar with a drop-down menu when the screen is narrow
- shrink the text size when the screen is narrow
- change the text color or background color for all screen widths, so that the text shows up clearly against the background even when it overflows
- make the nav bar background taller when the screen is narrow, so that all of the nav bar text always has a blue background behind it

I think I prefer the last one, but any of these is fine. Choose based on what seems easier or more fun to implement. :)

**Comment by mashton** [comment]
hi @sciepsilon! I think I can tackle this one. Right now a lot of the rest of the CSS depends on the header being a fixed height of 48px (using `calc` and such for other fixed elements), so the last bullet point you have might require a bigger CSS overhaul to how the 2-column content layout works. Because of that I'd probably go with (1) or (2) above. What's the minimum screen size that LingView should support? (It doesn't look like the pages are mobile-responsive, but maybe that's a goal for the future?)

**Comment by sciepsilon** [comment]
Mobile-responsive would be great, but it's not realistic unless you want to put a lot of work into it. We would have to rethink the whole sidebar thing for displaying stories, to start with. I would love to have this, but don't let me pressure you into a bigger project than you want to commit to!

I mostly notice this issue on my 13" laptop when I shrink LingView to a 5.7"-wide window during testing, and honestly I can work around it pretty easily. If you can make it work for a 5.5" width I'll consider it fixed.

**Comment by mashton** [comment]
Sounds good. Resolved with https://github.com/BrownCLPS/LingView/pull/72
